<?php foreach ($data as $field): ?>
  <span property="publisher" typeof="Organization">
  <?php $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
    <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
  <?php endif; ?>
  <?php $pubName = $field->getName(); if (!empty($pubName)): ?>
    <a property="name" href="<?=$this->record($this->driver)->getLink('publisher', $pubName)?>">
      <?=$this->escapeHtml($pubName)?>
    </a>
  <?php endif; ?>
  </span>
  
  <br/>
<?php endforeach; ?>
