<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent search-image-border">
  <h1 class="main-title">Sistema de busca integrada de materiais informacionais da UFRN</h1>
  <?php $this->slot('search-home-hero')->start() ?>
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?=$this->slot('search-home-hero')->end() ?>
</div>


<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
<div>

<div class="row">
<?php 
//Início dos cards 
?>
<div class="container bootstrap snippets bootdey">
    <div class="row home-cards">
        <div class="col-md-3 col-sm-6 col-xs-12">
	<a href="/Search/Results?lookfor=&type=AllFields&limit=40">
            <div class="panel panel-primary panel-colorful">
                <div class="panel-body text-center">
                	<p class="text-uppercase mar-btm text-sm">Documentos indexados</p>                	
			<i class="fa fa-globe fa-5x"></i>
                	<hr>
                	<p class="h2 text-thin" id="ufrn-total-count">-</p>
                	<small><span class="text-semibold"></span></small>
                </div>
            </div>
	</a>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
        	<a href="Search/Results?join=AND&filter%5B%5D=~format%3AmasterThesis&filter%5B%5D=~format%3AdoctoralThesis">
		<div class="panel  panel-primary panel-colorful">
        		<div class="panel-body text-center">
        			<p class="text-uppercase mar-btm text-sm">Teses e dissertações</p>
        			<i class="fa fa-graduation-cap fa-5x"></i>
        			<hr>
        			<p class="h2 text-thin" id="ufrn-repositorio-count">-</p>
        			<small><span class="text-semibold"></span></small>
        		</div>
        	</div>
		</a>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
		<a href="/Search/Results?type=AllFields&filter%5B%5D=institution%3APeriódicos+UFRN">
        	<div class="panel panel-primary panel-colorful">
        		<div class="panel-body text-center">
        			<p class="text-uppercase mar-btm text-sm">Portal de periódicos</p>
        			<i class="fa fa-newspaper-o fa-5x"></i>
        			<hr>
        			<p class="h2 text-thin" id="ufrn-portal-count">-</p>
        			<small><span class="text-semibold"></span></small>
        		</div>
        	</div>
		</a>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
        	<a href="/Search/Results?filter%5B%5D=institution%3AAcervo+SISBI&filter%5B%5D=format%3ALivro&type=AllFields">
		<div class="panel panel-primary panel-colorful">
        		<div class="panel-body text-center">
        			<p class="text-uppercase mar-btm text-sm">Acervo de livros do sisbi</p>
        			<i class="fa fa-book fa-5x"></i>
        			<hr>
        			<p class="h2 text-thin" id="ufrn-sigaa-count">-</p>
        			<small><span class="text-semibold"></span></small>
        		</div>
        	</div>
		</a>
        </div> 
    </div>
</div>


</div>

</div>
