<footer class="footer">
  <div class="container">
    <span>Desenvolvido pela Coordenadoria de Apoio Tecnológico da Biblioteca Central Zila Mamede - <?php echo date("Y"); ?></span>
  </div>
</footer>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-414K8G319Q"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-414K8G319Q');
</script>
